baseurl = "https://betweenthepipeoperator.netlify.com/"
title = "between the pipe operator"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Em."
googleAnalytics = "XXX"
enableEmoji = true

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Em"
    #profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "between the pipe operator"
    description = "Em. Data. Hockey."
    github = "https://github.com/em-ee"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/anyembutme"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
